version: '2'
services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=furls
      - MYSQL_PASSWORD=furls
      - MYSQL_DATABASE=furls
  web:
    build: .
    command: python manage.py runserver 0:8000
    environment:
      - DATABASE_URL=mysql://furls:furls@mysql/furls
    volumes:
      - .:/code
    ports:
      - "8000"
    depends_on:
      - mysql
