version: '2'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - "8000"
    depends_on:
      - db
